sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 264783
  huaweiobs:
    huaweicloud-sdk-ak: CMLYTEVUWIEZJMAGM0QU
    huaweicloud-sdk-sk: p2bUx6LvPQNnKmarIvej2GA2Zr6hPboMjtvuyasU
    endpoint: cn-east-3a
    bucket-name: pro-test-obs1