sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 264783
  huaweiobs:
    huaweicloud-sdk-ak:
    huaweicloud-sdk-sk:
    endpoint:
    bucket-name:
    remote_prefix: